### ISSUE TITLE
not able to find Pocket Network (POKT) token in the file 

### ISSUE THREAD

**Issue by Randomtrajectory** [alangrainger/cryptorates.ai#1]
detail of the token here 
https://www.coingecko.com/en/coins/pocket-network

**Comment by alangrainger** [comment]
Hi, it's right here in the Standard dataset:

![image](https://user-images.githubusercontent.com/16197738/163909812-0433e860-101d-4b7e-86ae-88225f03b8fd.png)

If you're using the Full dataset, just be aware that it includes the top 2000 coins only to keep the filesize manageable, and POKT is ranked number 2965:

https://coinmarketcap.com/currencies/pocket-network/

**Comment by Randomtrajectory** [comment]
Indeed, it seems CMC has not confirmed the market cap then ranking it at 2965 while coingecko did ranking them at 127 with marcap of 670mio.
anyway, thanks for looking at it so promptly, i will find a way to turn around it
and thanks for this useful link

**Comment by alangrainger** [comment]
Hmmm right you are. I'll check whether it would be better to switch to CoinGecko as a market data source. Better for POKT obviously, but I'll need to see if there are any other coins in the top 4000 that aren't also present on the CoinGecko top 4000 list.

**Comment by alangrainger** [comment]
Turns out CoinGecko tops out at coin number 3797, and doesn't provide market cap, circulating supply, or ranking data after that. So sadly a worse source overall than CoinMarketCap. One day I might have a look at Nomics, but for now we'll stick with CMC to get the larger range.

**Comment by alangrainger** [comment]
@Randomtrajectory I have checked CoinGecko data, and for the most part it seems comparable although with less precision on the prices. I have updated the dataset to use CoinGecko as the source, and we'll see how things go.

**Comment by Randomtrajectory** [comment]
Thanks!

**Comment by Randomtrajectory** [comment]
all working now
thanks Alan,
again thanks for the work on this database, i find it very useful
