### ISSUE TITLE
Missing All Time High (ATH)

### ISSUE THREAD

**Issue by geolectric** [alangrainger/cryptorates.ai#12]
We really need the All Time High (ATH) for this to be useful. Please consider adding.

**Comment by alangrainger** [comment]
This has been added :)  See the docs here:

https://cryptorates.ai/

## All-Time High (ATH) and Low (ATL)

The dates for these columns are in Unix epoch time. To convert to a normal Google Sheets date, use the EPOCHTODATE formula:

```
=EPOCHTODATE(K2)
```
