### ISSUE TITLE
CSv file update

### ISSUE THREAD

**Issue by OBASSHA** [alangrainger/cryptorates.ai#19]
Hi, been using your file on daily basis for about 2 years, its a bless,, just today noticed its last updated was 1700 of 9 Oct, please advise
Cheers

**Comment by alangrainger** [comment]
Thanks - looks like something is wrong at Cloudflare end. The data is updated but old data is being cached. I've cleared cache which has made the data up-to-date just as a quick workaround, and will figure out what's gone wrong.

**Comment by OBASSHA** [comment]
Many thanks for your quick response , just now checked the file, its updated.

**Comment by alangrainger** [comment]
It seems that just clearing the cache one time has solved the issue - the file is still up-to-date now with no other changes from me.

I'll close this, but please reply again if you see the file stop updating.

**Comment by OBASSHA** [comment]
noted , with thanks

**Comment by OBASSHA** [comment]
Hi Alan
The file update got stuck again Oct10 21:54, really sorry to disturb you on
this, but highly appreciate if you can fix it
Regards
Basha

**Comment by alangrainger** [comment]
No disturbing - I appreciate you letting me know :+1: 

I think I have identified the issue, so hopefully this is the last time.

**Comment by OBASSHA** [comment]
Great
