### ISSUE TITLE
Binance ETH staking (BETH) missing

### ISSUE THREAD

**Issue by SylarPower** [alangrainger/cryptorates.ai#2]
https://www.coingecko.com/en/coins/binance-eth-staking

I tried to pull all data (4000 coins) and it's not listed here,
I also tried with this formula but I had no luck 

> =QUERY(IMPORTDATA("https://cryptorates.ai/files/standard.csv", ",", "en_US"), "SELECT Col3 WHERE Col1 = 'BETH'", 0)

Same for HIGH and DAR but these are less important.

**Comment by alangrainger** [comment]
Hi @SylarPower . Looking on CoinGecko's website, that coin is not ranked and doesn't appear in the top 4000:

![image](https://user-images.githubusercontent.com/16197738/167827121-c6390a66-44f4-4267-9490-2cc210436881.png)

This would be why you can't see it in the top 4000 coins.

I've checked on CoinMarketCap also, and it doesn't appear to be listed there at all. If the coin reaches a high enough marketcap to be in the top 4000, it will then automatically appear in the CSV data source.

**Comment by SylarPower** [comment]
Thank you for the reply.
Isn't it possible to pull the data of a specific coin not in the top 4000 ?

**Comment by alangrainger** [comment]
Yes, you can do that directly with CoinGecko API:

https://blog.coingecko.com/import-coingecko-cryptocurrency-data-into-google-sheets/
