### ISSUE TITLE
Question: Request for Archived CSV Files

### ISSUE THREAD

**Issue by th1zan** [alangrainger/cryptorates.ai#20]
Hi, 

I would like to know if it is possible to access an older CSV file, specifically the archive of some prices at a specific date. I was wondering if you still rename and store the CSV files with a date, like:  
_https://cryptorates.ai/files/standard_20241009_0815.csv_ (date after updating).

I suppose you don't, but I just wanted to check! :-)

Thanks!

**Comment by alangrainger** [comment]
Sorry no I don't have that, but you should be able to get historical data for free from CoinMarketCap or CoinGecko.
