### ISSUE TITLE
Error - Could not fetch url: https://cryptorates.ai/files/full.csv

### ISSUE THREAD

**Issue by minduxas** [alangrainger/cryptorates.ai#22]
Error
Could not fetch url: https://cryptorates.ai/files/full.csv

**Comment by alangrainger** [comment]
Update: It looks like Google has something broken inside their own Sheets cache.

Add any query string to the URL to bypass their cache:

```
https://cryptorates.ai/files/full.csv?123
```

I'm sure the original URL will be functional again soon when they refresh their cache.

---

It's working fine for me, what error are you seeing?

Can you load it from your browser?

**Comment by minduxas** [comment]
In the web:

￼

In my sheet:

￼


Mindaugas
+37061881270

**Comment by JoeDotps1** [comment]
I'm seeing the same thing.  CSV accessible fine directly but failing when accessed via google sheets.  perhaps some google servers got blocklisted? 
<img width="157" alt="Screenshot 2024-11-12 123817" src="https://github.com/user-attachments/assets/3cb9cdfc-ac44-4476-aee8-dd3dd83c983f">

**Comment by alangrainger** [comment]
Try adding any query string to it, eg:

```
https://cryptorates.ai/files/full.csv?123
```

**Comment by JoeDotps1** [comment]
that works but I'm puzzled as to why.  should we implement that as a workaround or is that just a troubleshooting step?

**Comment by alangrainger** [comment]
Seems like Google has cached something that is broken. It will fall out of their cache soon enough. You can leave it with the query string or remove it in a few hours and see if Google has fixed things at their end.

**Comment by JoeDotps1** [comment]
Thanks for the quick response & workaround!  And thanks for providing this service!!

**Comment by alangrainger** [comment]
Appears to be resolved at Google's end now.
