### ISSUE TITLE
Lots of Top Coins Missing

### ISSUE THREAD

**Issue by tiequan12345** [alangrainger/cryptorates.ai#5]
Hi there, love the tool and it works great for a lot of my purposes, your description says it's for the top 5000 coins on Coingecko but I noticed a bunch that are top 1000 that aren't on there.  For example:

stATOM - largest liquid staked ATOM token on Cosmos, ranked #581 on Coingecko but missing on the CSV:
https://www.coingecko.com/en/coins/stride-staked-atom

Is there any code that can be shared so I can customize a further list of coins that aren't on your CSV for my own purposes?  I use google sheets for PNL and the tool works great but there's still a decent number of tokens that I need to go through manually pulling prices and dealing with Loading... issues

**Comment by alangrainger** [comment]
The top 5000 coin list is the CoinMarketCap list.

It's the same problem if I use CoinGecko instead - there are ones represented on CMC that _aren't_ on CoinGecko. Either way I'm damned if I do damned if I don't.

**Comment by 0xFloyd** [comment]
just want to say thank you for building this, its amazing! do you accept donations?
