### ISSUE TITLE
Question: All time high for each coin?

### ISSUE THREAD

**Issue by prismanet** [alangrainger/cryptorates.ai#7]
Hi,
I found your cryptorates.ai site searching on Google. What you have done is great and thanks for that. I'd like to know if it would be possible to add a new column for All Time High (ATH) of each coin to your Full.csv export?
Let me know if you have questions.
Regards,
Prismanet

**Comment by chefsas** [comment]
I'd like to second the request for this item. If I had ATH (may as well add ATL while you're at it), I could use that value for certain projections and/or rules around my portfolio.

PS. Thank you so much for going through the effort to put this tool out there. It's incredibly helpful and simplifies much of the organization of my mining operations.

**Comment by alangrainger** [comment]
This has been added :)  See the docs here:

https://cryptorates.ai/

## All-Time High (ATH) and Low (ATL)

The dates for these columns are in Unix epoch time. To convert to a normal Google Sheets date, use the EPOCHTODATE formula:

```
=EPOCHTODATE(K2)
```

**Comment by alangrainger** [comment]
This has been added :)  @chefsas please pass it around to your mining contacts - the more people using this the merrier. As the data is cached for free by Cloudflare it doesn't cost anything to have a million people using this vs 5 people.

See the docs here: https://cryptorates.ai/

## All-Time High (ATH) and Low (ATL)

The dates for these columns are in Unix epoch time. To convert to a normal Google Sheets date, use the EPOCHTODATE formula:

```
=EPOCHTODATE(K2)
```

**Comment by chefsas** [comment]
This is awesome! Thanks so much!


-Scott
